// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr6DrtqkdxHdLCbuLaBobvmrdlhDgJPgM',
    appId: '1:664395123621:web:cd1fa01028770e207c364c',
    messagingSenderId: '664395123621',
    projectId: 'kasir-fcb3c',
    authDomain: 'kasir-fcb3c.firebaseapp.com',
    storageBucket: 'kasir-fcb3c.appspot.com',
    measurementId: 'G-MR65ESJSZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqIsLeoT09HHh-XEkgo4WKQHCt4j-9cqw',
    appId: '1:664395123621:android:0deaa8057b8e68ef7c364c',
    messagingSenderId: '664395123621',
    projectId: 'kasir-fcb3c',
    storageBucket: 'kasir-fcb3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7AbMbJrabBfgQCsWfKsf0C4nOCQKnlWc',
    appId: '1:664395123621:ios:eb9e3b8801b7800f7c364c',
    messagingSenderId: '664395123621',
    projectId: 'kasir-fcb3c',
    storageBucket: 'kasir-fcb3c.appspot.com',
    iosBundleId: 'com.example.fireflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7AbMbJrabBfgQCsWfKsf0C4nOCQKnlWc',
    appId: '1:664395123621:ios:eb9e3b8801b7800f7c364c',
    messagingSenderId: '664395123621',
    projectId: 'kasir-fcb3c',
    storageBucket: 'kasir-fcb3c.appspot.com',
    iosBundleId: 'com.example.fireflutter',
  );
}
